// src/pages/index.svelte
<script lang="typescript">
import List from '../components/List.svelte';
import NewItem from '../components/NewItem.svelte';
import DisplayCounts from '../components/DisplayCounts.svelte';

import todos from '../stores/todos';
</script>

<div>
    <h1 class="font-extrabold text-3xl tracking-wider text-center underline">
        TODOs
    </h1>

    <List items={$todos} />

    <NewItem on:add={todos.addItem} />

    <DisplayCounts total={$todos.length} remaining={todos.incompleteCount} />
</div>

// pages/index.vue
<template>
  <div class="w-1/4">
    <h1 class="font-extrabold text-3xl tracking-wider text-center underline">
      TODOs
    </h1>

    <List :items="todos" v-bind="{ toggleComplete, removeItem }" />

    <NewItem @submit="addItem" />

    <DisplayCounts :total="todos.length" :remaining="incompleteCount" />
  </div>
</template>

<script lang="ts">
import { createComponent } from '@vue/composition-api';
import List from '@/components/List.vue';
import NewItem from '@/components/NewItem.vue';
import DisplayCounts from '@/components/DisplayCounts.vue';
import useTodoList from '@/hooks/useTodoList';

export default createComponent({
  setup() {
    const {
      todos,
      addItem,
      toggleComplete,
      removeItem,
      incompleteCount
    } = useTodoList();

    return { todos, addItem, toggleComplete, removeItem, incompleteCount };
  },

  components: { List, NewItem, DisplayCounts }
});
</script>
